services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FIRESTORE_PROJECT_ID=milkguard2
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
