services:
  web:
    build: ./backend
    ports:
      - "5555:5000" # mapping the external port 5555 to container's internal port 5000 (on your computer use localhost:5555)
  frontend:
    build: ./frontend
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000 (on your computer use localhost:3333)
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5555 # this defines the URL the frontend makes requests to
    depends_on:
      - web # this depends on the backend container (which we called web at the top of this file)