services:
  db:
    image: postgres:14.0
    environment:
      POSTGRES_DB: milk_checker
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Expose PostgreSQL default port on localhost
    volumes:
      - ./backend/volumes/postgres:/var/lib/postgresql/data  # Persistent data storage
  web:
    build: ./backend
    ports:
      - "5555:5000" # mapping the external port 5555 to container's internal port 5000 (on your computer use localhost:5555)
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/milk_checker # Ensuring backend connects to db service
    depends_on:
      - db  # Ensure the database is ready before starting the backend
  frontend:
    build: ./frontend
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000 (on your computer use localhost:3333)
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5555 # this defines the URL the frontend makes requests to
    depends_on:
      - web # this depends on the backend container (which we called web at the top of this file)