services:

  backend:
    build: ./backend
    ports:
     - "5001:5001"
    environment:
     - FIRESTORE_PROJECT_ID=milkguard-fe148
    volumes:
     - ./backend:/app

  frontend:
    build: ./frontend
    ports:
     - "3000:3000"
    depends_on:
     - backend