services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FIRESTORE_PROJECT_ID=milkguard2
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: python app.py
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
